#Universal Grid Options
#
#Whether the Wireless Universal Grid uses energy
useEnergy = false
#
#The energy used by the Wireless Universal Grid to clear the crafting matrix
#Range: > 0
clearUsage = 0
#
#The energy used by the Wireless Universal Grid to craft an item
#Range: > 0
craftUsage = 0
#
#The energy used by the Universal Crafting Grid to open
#Range: > 0
openUsage = 0
#
#The energy capacity of the Universal Crafting Grid
#Range: > 0
capacity = 6400

